development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: facescrape_development
  pool: 5
  username: gbishop
  password: du3aZ3ch

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: facescrape_test
  pool: 5
  username: root
  password: du3aZ3ch

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: facescrape_production
  pool: 5
  username: root
  password: du3aZ3ch

